name: CI

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  install:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 16
      - name: Install
        run: npm ci
      - name: Cache results
        uses: actions/cache@v2
        id: cache-results
        with:
          path: |
            node_modules
          key: ${{ github.sha }}
  statoscope:
    needs:
      - install
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 16
      - name: Restore cache
        uses: actions/cache@v2
        id: restore-cache
        with:
          path: |
            node_modules
          key: ${{ github.sha }}
      - name: Query stats
        if: "github.event_name == 'pull_request'"
        run: cat .github/workflows/statoscope-comment.jora | npx --no-install @statoscope/cli query --input demo-stats.json > result.json
      - name: Comment PR
        if: "github.event_name == 'pull_request'"
        uses: actions/github-script@v5
        with:
          script: |
            const createStatoscopeComment = require('./scripts/createStatoscopeComment');
            await createStatoscopeComment({github, context, core})
